language: android
env:
  matrix:
    - ANDROID_SDKS=android-23,sysimg-23  ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
